// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 15.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Globalization;
using System.Text;

namespace Microsoft.DbContextPackage.Utilities
{
    /// <summary>
    ///     Class to produce the template output
    /// </summary>
#line 1 "C:\git\aspnet\EntityFramework6\src\PowerTools\Utilities\VBViewGenerator.tt"
    [GeneratedCode("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public partial class VBViewGenerator : VBViewGeneratorBase
    {
        /// <summary>
        ///     Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            Write(@"'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.CodeDom.Compiler
Imports System.Data.Entity.Core.Metadata.Edm
Imports System.Data.Entity.Infrastructure.MappingViews

<Assembly: DbMappingViewCacheTypeAttribute(
    GetType(");

#line 19 "C:\git\aspnet\EntityFramework6\src\PowerTools\Utilities\VBViewGenerator.tt"
            Write(ToStringHelper.ToStringWithCulture(ContextTypeName));

#line default
#line hidden
            Write("),\r\n    GetType(Edm_EntityMappingGeneratedViews.ViewsForBaseEntitySets");

#line 20 "C:\git\aspnet\EntityFramework6\src\PowerTools\Utilities\VBViewGenerator.tt"
            Write(ToStringHelper.ToStringWithCulture(MappingHashValue));

#line default
#line hidden
            Write("))>\r\n\r\nNamespace Edm_EntityMappingGeneratedViews\r\n\r\n    \'\'\' <summary>\r\n    \'\'\' Im" +
                  "plements a mapping view cache.\r\n    \'\'\' </summary>\r\n    <GeneratedCode(\"Entity F" +
                  "ramework 6 Power Tools\", \"0.9.2.0\")>\r\n    Friend NotInheritable Class ViewsForBa" +
                  "seEntitySets");

#line 28 "C:\git\aspnet\EntityFramework6\src\PowerTools\Utilities\VBViewGenerator.tt"
            Write(ToStringHelper.ToStringWithCulture(MappingHashValue));

#line default
#line hidden
            Write(@"
        Inherits DbMappingViewCache

        ''' <summary>
        ''' Gets a hash value computed over the mapping closure.
        ''' </summary>
        Public Overrides ReadOnly Property MappingHashValue As String
            Get
                Return """);

#line 36 "C:\git\aspnet\EntityFramework6\src\PowerTools\Utilities\VBViewGenerator.tt"
            Write(ToStringHelper.ToStringWithCulture(MappingHashValue));

#line default
#line hidden
            Write(@"""
            End Get
        End Property

        ''' <summary>
        ''' Gets a view corresponding to the specified extent.
        ''' </summary>
        ''' <param name=""extent"">The extent.</param>
        ''' <returns>The mapping view, or null if the extent is not associated with a mapping view.</returns>
        Public Overrides Function GetView(extent As EntitySetBase) As DbMappingView
            If extent Is Nothing Then
                Throw New ArgumentNullException(""extent"")
            End If

            Dim extentName = extent.EntityContainer.Name & ""."" & extent.Name
");

#line 51 "C:\git\aspnet\EntityFramework6\src\PowerTools\Utilities\VBViewGenerator.tt"

            var index = 0;
            foreach (var view in Views)
            {
#line default
#line hidden
                Write("\r\n            If extentName = \"");

#line 57 "C:\git\aspnet\EntityFramework6\src\PowerTools\Utilities\VBViewGenerator.tt"
                this.Write(ToStringHelper.ToStringWithCulture(view.Key.EntityContainer.Name + "." + view.Key.Name));

#line default
#line hidden
                Write("\" Then\r\n                Return GetView");

#line 58 "C:\git\aspnet\EntityFramework6\src\PowerTools\Utilities\VBViewGenerator.tt"
                Write(ToStringHelper.ToStringWithCulture(index));

#line default
#line hidden
                Write("()\r\n            End If\r\n");

#line 60 "C:\git\aspnet\EntityFramework6\src\PowerTools\Utilities\VBViewGenerator.tt"

                index++;
            }


#line default
#line hidden
            Write("\r\n            Return Nothing\r\n        End Function\r\n");

#line 67 "C:\git\aspnet\EntityFramework6\src\PowerTools\Utilities\VBViewGenerator.tt"

            index = 0;
            foreach (var view in Views)
            {
                var entitySql = string.Join(
                    "\" & vbCrLf &\r\n                \"",
                    view.Value.EntitySql.Split(new[] {Environment.NewLine}, StringSplitOptions.None));


#line default
#line hidden
                Write("\r\n        \'\'\' <summary>\r\n        \'\'\' Gets the view for ");

#line 77 "C:\git\aspnet\EntityFramework6\src\PowerTools\Utilities\VBViewGenerator.tt"
                this.Write(ToStringHelper.ToStringWithCulture(view.Key.EntityContainer.Name + "." + view.Key.Name));

#line default
#line hidden
                Write(".\r\n        \'\'\' </summary>\r\n        \'\'\' <returns>The mapping view.</returns>\r\n    " +
                      "    Private Shared Function GetView");

#line 80 "C:\git\aspnet\EntityFramework6\src\PowerTools\Utilities\VBViewGenerator.tt"
                Write(ToStringHelper.ToStringWithCulture(index));

#line default
#line hidden
                Write("() As DbMappingView\r\n            Return New DbMappingView(\r\n                \"");

#line 82 "C:\git\aspnet\EntityFramework6\src\PowerTools\Utilities\VBViewGenerator.tt"
                this.Write(ToStringHelper.ToStringWithCulture(entitySql));

#line default
#line hidden
                Write("\")\r\n        End Function\r\n");

#line 84 "C:\git\aspnet\EntityFramework6\src\PowerTools\Utilities\VBViewGenerator.tt"

                index++;
            }


#line default
#line hidden
            Write("    End Class\r\nEnd Namespace\r\n");
            return GenerationEnvironment.ToString();
        }

        public string ContextTypeName { get; set; }
        public string MappingHashValue { get; set; }
        public dynamic Views { get; set; }
    }

#line default
#line hidden

    #region Base class

    /// <summary>
    ///     Base class for this transformation
    /// </summary>
    [GeneratedCode("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public class VBViewGeneratorBase
    {
        #region Fields

        private StringBuilder generationEnvironmentField;
        private CompilerErrorCollection errorsField;
        private List<int> indentLengthsField;
        private bool endsWithNewline;

        #endregion

        #region Properties

        /// <summary>
        ///     The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected StringBuilder GenerationEnvironment
        {
            get
            {
                if (generationEnvironmentField == null) generationEnvironmentField = new StringBuilder();
                return generationEnvironmentField;
            }
            set => generationEnvironmentField = value;
        }

        /// <summary>
        ///     The error collection for the generation process
        /// </summary>
        public CompilerErrorCollection Errors
        {
            get
            {
                if (errorsField == null) errorsField = new CompilerErrorCollection();
                return errorsField;
            }
        }

        /// <summary>
        ///     A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private List<int> indentLengths
        {
            get
            {
                if (indentLengthsField == null) indentLengthsField = new List<int>();
                return indentLengthsField;
            }
        }

        /// <summary>
        ///     Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent { get; private set; } = "";

        /// <summary>
        ///     Current transformation session
        /// </summary>
        public virtual IDictionary<string, object> Session { get; set; }

        #endregion

        #region Transform-time helpers

        /// <summary>
        ///     Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend)) return;
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (GenerationEnvironment.Length == 0
                || endsWithNewline)
            {
                GenerationEnvironment.Append(CurrentIndent);
                endsWithNewline = false;
            }

            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(Environment.NewLine, StringComparison.CurrentCulture)) endsWithNewline = true;
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if (CurrentIndent.Length == 0)
            {
                GenerationEnvironment.Append(textToAppend);
                return;
            }

            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(Environment.NewLine, Environment.NewLine + CurrentIndent);
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (endsWithNewline)
                GenerationEnvironment.Append(textToAppend, 0, textToAppend.Length - CurrentIndent.Length);
            else
                GenerationEnvironment.Append(textToAppend);
        }

        /// <summary>
        ///     Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            Write(textToAppend);
            GenerationEnvironment.AppendLine();
            endsWithNewline = true;
        }

        /// <summary>
        ///     Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            Write(string.Format(CultureInfo.CurrentCulture, format, args));
        }

        /// <summary>
        ///     Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            WriteLine(string.Format(CultureInfo.CurrentCulture, format, args));
        }

        /// <summary>
        ///     Raise an error
        /// </summary>
        public void Error(string message)
        {
            var error = new CompilerError();
            error.ErrorText = message;
            Errors.Add(error);
        }

        /// <summary>
        ///     Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            var error = new CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            Errors.Add(error);
        }

        /// <summary>
        ///     Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if (indent == null) throw new ArgumentNullException("indent");
            CurrentIndent = CurrentIndent + indent;
            indentLengths.Add(indent.Length);
        }

        /// <summary>
        ///     Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            var returnValue = "";
            if (indentLengths.Count > 0)
            {
                var indentLength = indentLengths[indentLengths.Count - 1];
                indentLengths.RemoveAt(indentLengths.Count - 1);
                if (indentLength > 0)
                {
                    returnValue = CurrentIndent.Substring(CurrentIndent.Length - indentLength);
                    CurrentIndent = CurrentIndent.Remove(CurrentIndent.Length - indentLength);
                }
            }

            return returnValue;
        }

        /// <summary>
        ///     Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            indentLengths.Clear();
            CurrentIndent = "";
        }

        #endregion

        #region ToString Helpers

        /// <summary>
        ///     Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private IFormatProvider formatProviderField = CultureInfo.InvariantCulture;

            /// <summary>
            ///     Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public IFormatProvider FormatProvider
            {
                get => formatProviderField;
                set
                {
                    if (value != null) formatProviderField = value;
                }
            }

            /// <summary>
            ///     This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if (objectToConvert == null) throw new ArgumentNullException("objectToConvert");
                var t = objectToConvert.GetType();
                var method = t.GetMethod("ToString", new[]
                {
                    typeof(IFormatProvider)
                });
                if (method == null)
                    return objectToConvert.ToString();
                return (string) method.Invoke(objectToConvert, new object[]
                {
                    formatProviderField
                });
            }
        }

        /// <summary>
        ///     Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper { get; } = new ToStringInstanceHelper();

        #endregion
    }

    #endregion
}